server:
    port: 8080

spring:
    datasource:
      name: his
      url: jdbc:mysql://localhost:3306/his?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      password: root
      username: root
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
    type-aliases-package: com.his.pojo
    configuration:
        mapUnderscoreToCamelCase: true

logging:
  level:
    com.his.mapper: trace

